# Generated by Django 4.2.3 on 2023-07-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=32)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=4)),
                ('payment_status', models.BooleanField()),
                ('order_status', models.CharField(max_length=32)),
                ('payment_method', models.CharField(max_length=32)),
            ],
        ),
    ]
